services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  timotewbcom:
    image: ghcr.io/timotewb/timotewbcom:vps-prod
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.timotewbcom.rule=PathPrefix(`/`)"
      - "traefik.http.services.timotewbcom.loadbalancer.server.port=3001"
      - "com.centurylinklabs.watchtower.enable=true"
